language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly" # currently points to 3.7-dev
before_install:
    - "pip install Cython"
    - "pip install numpy"
install:
    - "pip install -r requirements-test.txt"
script:
    PYTHONPATH=. py.test --cov
after_success:
    coveralls
